<a href="https://colab.research.google.com/github/Daria720/NM/blob/main/%D0%9B%D0%A04_%D0%93%D0%BE%D0%BC%D0%BE%D0%BD%D1%8E%D0%BA_%D0%94_5%D0%B2%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

була присутня на парі

In [2]:
#!pip install numpy

In [4]:
import numpy as np

numpy_version = np.__version__
numpy_version

'2.0.2'

In [5]:
matrix = np.random.randint(1, 6, size=(3,3))

matrix

array([[2, 4, 4],
       [2, 5, 2],
       [2, 3, 2]])

In [6]:
det = np.linalg.det(matrix)
det

np.float64(-7.999999999999998)

In [7]:
product = np.prod(matrix)
product

np.int64(7680)

In [9]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3


np.int64(7680)

In [11]:
sum_1 = np.sum(matrix)
sum_1

np.int64(26)

In [12]:
np.max(matrix)

np.int64(5)

In [13]:
np.min(matrix)

np.int64(2)

In [15]:
np.mean(matrix)

np.float64(2.888888888888889)

In [16]:
np.sqrt(matrix)

array([[1.41421356, 2.        , 2.        ],
       [1.41421356, 2.23606798, 1.41421356],
       [1.41421356, 1.73205081, 1.41421356]])

In [17]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)
print("сума елементів кожного рядка:")
print(row_sums)

сума елементів кожного рядка:
[[10]
 [ 9]
 [ 7]]


In [19]:
vector = np.random.randint(0, 10, size=25)
vector

array([6, 4, 4, 9, 3, 3, 5, 5, 9, 4, 6, 5, 5, 0, 4, 4, 5, 4, 7, 1, 9, 0,
       3, 3, 9])

In [22]:
sorted_vector = np.sort(vector)[::-1]
sorted_vector

array([9, 9, 9, 9, 7, 6, 6, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3,
       1, 0, 0])

In [23]:
a = np.array([[14, 4, 6], [5, -3, 2], [10, -11, 5]])
b = np.array([30, 15, 36])

x = np.linalg.solve(a, b)
print('Вбудована функція', x)

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print('Матричний метод', x1)

Вбудована функція [ 2. -1.  1.]
Матричний метод [ 2. -1.  1.]


In [24]:
# Метод Крамера
def kramer(a, b):
    det_a = np.linalg.det(a)
    if det_a != 0:
        solutions = []
        for i in range(len(a)):
            modified_a = np.copy(a)
            modified_a[:, i] = b
            solutions.append(round(np.linalg.det(modified_a) / det_a, 1))

        print('Solving a system of linear algebraic equations by Cramer\'s method:')
        #print('x =', solutions)

    else:
        print('Determinant equals zero, the system has no solutions')
    return solutions
# Виклик функцій для розв'язання системи
print(kramer(a, b))


Solving a system of linear algebraic equations by Cramer's method:
[np.float64(2.0), np.float64(-1.0), np.float64(1.0)]
